fixed country code and phone no. population logic
DrKLO/Telegram pull request #1624
Opened 2021-03-21 09:58 UTC by rafismugmug

When people try to log in or sign up, the characters in the phone number are used to set the country code, which is incorrect.
This results in country code and phone number being populated incorrectly. 

Phone number below is : 6692049100
Country is US

However, 66 is taken for country

![image](https://user-images.githubusercontent.com/48738678/111900680-2cff8900-89f1-11eb-84c3-c7416a27e1b0.png)

2021-03-21 10:20 UTC, rafismugmug commented
@DrKLO

2021-03-22 02:29 UTC, Luxxy-787 commented
Try manually

2021-03-27 02:08 UTC, Mahmed21 requested changes
Leavae

2021-04-05 12:25 UTC, Nirzak reviewed
Well, I didn't get your point. I am using the latest Telegram app on my mobile and I always got the correct country code by selecting country. Here on your image, you have selected Thailand, and +66 is the correct code for Thailand. So, what's the problem? I tried it just a few moments ago. And it also gives +1 as a country code when selected USA as a country. So I think it's working just fine.

2021-04-05 20:23 UTC, rafismugmug commented
When you come to login screen, The country code should be automatically populated from the sim card or phone number. Here country code should have been +1, but in the screenshot, it's +66 Thailand, which is incorrect. You don't need to manually select that. The PR fixes the country code population logic, so that correct country code is detected from the phone.

2021-04-05 21:07 UTC, Nirzak commented
> When you come to login screen, The country code should be automatically populated from the sim card or phone number. Here country code should have been +1, but in the screenshot, it's +66 Thailand, which is incorrect. You don't need to manually select that. The PR fixes the country code population logic, so that correct country code is detected from the phone.

Yeah my bad actually. Now I see.

2021-04-05 21:08 UTC, Nirzak approved these changes

2021-07-07 06:55 UTC, closed without merging